-- 코드를 입력하세요
SELECT f.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS FIRST_TOTAL FROM FIRST_HALF GROUP BY FLAVOR) f
JOIN 
(SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL FROM JULY GROUP BY FLAVOR) j
ON f.FLAVOR = j.FLAVOR
ORDER BY (f.FIRST_TOTAL + j.JULY_TOTAL) DESC
LIMIT 3